apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-catalog
  template:
    metadata:
      labels:
        app: book-catalog
    spec:
      containers: 
      - name: book-catalog
        image: $CONTAINER_REGISTRY/book-catalog:$VERSION
        imagePullPolicy: IfNotPresent
        env:
        - name: PORT
          value: "4000"  # PORT for book-catalog container
---
apiVersion: v1
kind: Service
metadata:
  name: book-catalog
spec:
  selector:
    app: book-catalog
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080       # Changed external port for book-catalog to 8080
      targetPort: 4000 # Routes traffic to port 4000 inside the container
