apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-management
  template:
    metadata:
      labels:
        app: inventory-management
    spec:
      containers: 
      - name: inventory-management
        image: $CONTAINER_REGISTRY/inventory-management:$VERSION
        imagePullPolicy: IfNotPresent
        env:
        - name: PORT
          value: "5000"  # Changed PORT for inventory-management container
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-management
spec:
  selector:
    app: inventory-management
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80         # Exposes on port 80
      targetPort: 5000 # Routes traffic to port 5000 inside the container
